package com.example.petadoption.vo;

import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

@DisplayName("统一响应结果测试")
public class ResultTest {

    @Test
    @DisplayName("成功响应-无数据")
    void testSuccessWithoutData() {
        Result<Void> result = Result.success();

        assertNotNull(result);
        assertEquals(200, result.getCode());
        assertEquals("操作成功", result.getMessage());
        assertNull(result.getData());
        assertNotNull(result.getTimestamp());
    }

    @Test
    @DisplayName("成功响应-带数据")
    void testSuccessWithData() {
        String data = "test data";

        Result<String> result = Result.success(data);

        assertNotNull(result);
        assertEquals(200, result.getCode());
        assertEquals("操作成功", result.getMessage());
        assertEquals(data, result.getData());
        assertNotNull(result.getTimestamp());
    }

    @Test
    @DisplayName("成功响应-自定义消息和数据")
    void testSuccessWithMessageAndData() {
        String message = "自定义成功消息";
        String data = "test data";

        Result<String> result = Result.success(message, data);

        assertNotNull(result);
        assertEquals(200, result.getCode());
        assertEquals(message, result.getMessage());
        assertEquals(data, result.getData());
        assertNotNull(result.getTimestamp());
    }

    @Test
    @DisplayName("错误响应-仅消息")
    void testErrorWithMessage() {
        String message = "操作失败";

        Result<Void> result = Result.error(message);

        assertNotNull(result);
        assertEquals(500, result.getCode());
        assertEquals(message, result.getMessage());
        assertNull(result.getData());
        assertNotNull(result.getTimestamp());
    }

    @Test
    @DisplayName("错误响应-错误码和消息")
    void testErrorWithCodeAndMessage() {
        Integer code = 1001;
        String message = "用户已存在";

        Result<Void> result = Result.error(code, message);

        assertNotNull(result);
        assertEquals(code, result.getCode());
        assertEquals(message, result.getMessage());
        assertNull(result.getData());
        assertNotNull(result.getTimestamp());
    }

    @Test
    @DisplayName("错误响应-错误码、消息和数据")
    void testErrorWithCodeMessageAndData() {
        Integer code = 1001;
        String message = "用户已存在";
        String data = "错误详情";

        Result<String> result = Result.error(code, message, data);

        assertNotNull(result);
        assertEquals(code, result.getCode());
        assertEquals(message, result.getMessage());
        assertEquals(data, result.getData());
        assertNotNull(result.getTimestamp());
    }

    @Test
    @DisplayName("构造函数测试")
    void testConstructor() {
        Integer code = 200;
        String message = "测试消息";
        String data = "测试数据";

        Result<String> result = new Result<>(code, message, data);

        assertEquals(code, result.getCode());
        assertEquals(message, result.getMessage());
        assertEquals(data, result.getData());
        assertNotNull(result.getTimestamp());
    }

    @Test
    @DisplayName("默认构造函数测试")
    void testDefaultConstructor() {
        Result<String> result = new Result<>();

        assertNull(result.getCode());
        assertNull(result.getMessage());
        assertNull(result.getData());
        assertNotNull(result.getTimestamp());
    }

    @Test
    @DisplayName("时间戳自动生成")
    void testTimestampAutoGenerated() {
        long beforeCreation = System.currentTimeMillis();
        
        Result<Void> result1 = Result.success();
        Result<Void> result2 = Result.success();

        long afterCreation = System.currentTimeMillis();

        assertTrue(result1.getTimestamp() >= beforeCreation);
        assertTrue(result1.getTimestamp() <= afterCreation);
        assertTrue(result2.getTimestamp() >= beforeCreation);
        assertTrue(result2.getTimestamp() <= afterCreation);
    }

    @Test
    @DisplayName("链式调用测试")
    void testChainedCalls() {
        Result<String> result = Result.success("成功");

        assertNotNull(result.getData());
        assertEquals(200, result.getCode());
    }

    @Test
    @DisplayName("复杂对象数据测试")
    void testComplexObjectData() {
        UserVO userVO = new UserVO();
        userVO.setUserId("user123");
        userVO.setUsername("testuser");
        userVO.setNickname("测试用户");

        Result<UserVO> result = Result.success(userVO);

        assertNotNull(result.getData());
        assertEquals("user123", result.getData().getUserId());
        assertEquals("testuser", result.getData().getUsername());
    }

    @Test
    @DisplayName("不同错误码测试")
    void testDifferentErrorCodes() {
        Result<Void> result401 = Result.error(401, "未授权");
        Result<Void> result403 = Result.error(403, "无权限");
        Result<Void> result404 = Result.error(404, "资源不存在");
        Result<Void> result500 = Result.error(500, "系统错误");

        assertEquals(401, result401.getCode());
        assertEquals(403, result403.getCode());
        assertEquals(404, result404.getCode());
        assertEquals(500, result500.getCode());
    }
}
